encoding: utf-8

# SEO相关信息
title: n1cef1sh's Blog
description: n1cef1sh 的个人博客
keywords: Blog
author: nicefish
footerText: 'Copyright © 2020 nicefish'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'cli.bat', 'dist.tar.gz']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://www.nicefish.xyz/'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/product/276517

# 菜单
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 腾讯MTA移动分析,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extMTA: true

# 百度收录自动推送,不需要请设置为false
extBaidu: true

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# Valine评论系统开关
# Valine.
# You can get your appid and appkey from https://leancloud.app
# more info please open https://valine.js.org
valine:
  enable: true
  appid:  F6oYAOQ0i49VSLjrIqMROjXJ-gzGzoHsz # your leancloud app id
  appkey: bSK0Qzjj9p0PPkWNYHEl3VdP # your leancloud app key
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki，v1.4.0+ 已废弃
  verify: false # Verification code，v1.4.0+ 已废弃
  placeholder: 在此处留言 # comment box placeholder
  avatar:   # gravatar style
  guest_info: 昵称,邮件,网址 # custom comment header
  pageSize: 10 # pagination size
  # path: window.location.pathname #  v1.4.0+不要使用参数“app_key: 'LHvLGcwcauE5B2JpMxJ3lbtF',”
  recordIP: true # 是否记录评论者IP


# 友情链接
links:
  - title: p0desta
    url: http://p0desta.com/
  
